### ISSUE TITLE
Autohotkey script has 'Return' as text

### ISSUE THREAD

**Issue by LarveyOfficial** [Michigan-Tech-Courses/frontend#42]
I don't know if this is intentional or not, as I have not properly tested it, but when using the AutoHotkey Script it types an extra "Return" as seen below

https://user-images.githubusercontent.com/39219859/199868080-f3fa1f91-ad8a-4bb4-9568-980a84a49533.mp4

I was just wondering why that is. And if its needed or not.

Thanks

**Comment by codetheweb** [comment]
Apologies for the very late response on this.

This was a bug, thanks for reporting--should be fixed now.
