### ISSUE TITLE
The slider in the basket doesn't move all the way to the left (Macbook)

### ISSUE THREAD

**Issue by MichealMeow** [Michigan-Tech-Courses/frontend#43]
I'm on an M1 Macbook Air, and whenever I try to slide all the way to the left to see the names of the courses, the slider gets stuck. Only happens in basket. I tried this on Firefox and Opera GX, and I ran into the same problem.

<img width="1440" alt="Screen Shot 2023-10-16 at 6 42 59 PM" src="https://github.com/Michigan-Tech-Courses/frontend/assets/95190660/8734e402-6c53-4cb8-b3b2-415c6eeb2cc6">

**Comment by codetheweb** [comment]
The scrollbar isn't getting stuck, but I do see content being cut off if that's what you mean.

**Comment by codetheweb** [comment]
The scrollbar isn't getting stuck, but I do see content being cut off if that's what you mean.
